# REST Client (extension vscode) un bon remplaçant pour postman
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:3000/api/stocks/
Authorization: Bearer the_token...

###
POST http://localhost:3000/api/stocks/
Content-Type: application/json
Authorization: Bearer the_token...

{
    "title": "stock02 title",
    "typeStock": "type stock02",
    "description": "description stock 02",
    "restaurantId": 9
}


###
PUT http://localhost:3000/api/stocks/
Content-Type: application/json
Authorization: Bearer the_token...

{
    "id": 3,
    "typeStock": "modification du type stock d'id 3",
    "restaurantId": 9
}

###
DELETE http://localhost:3000/api/stocks/1005
Authorization: Bearer the_token...